#Base image
FROM mysql:5.7.28
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=devopsclass
ENV MYSQL_USER=ranjit
ENV MYSQL_PASSWORD=Sunday@2019
#COPY
COPY ./dump/devopsclass.sql /docker-entrypoint-initdb.d
