---
#version: "3"
services:
  db:
      image: lipughadei/mysql:v1.0
      ports:
        - "3306:3306"
  ui:
      image: lipughadei/tomcat:v1.0
      ports:
        - "8080:8080"
      links:
        - db:db 
        