---
- hosts: module1
  become: true #become: false
  tasks:
    - name: checkout github repository
      git:
        repo: git@github.com:Lipughadei/LoginWebApp.git
        dest: /home/ec2-user/jenkins/workspace/pipeline_job1
    - name: docker compose upg
      shell:
        chdir: /home/ec2-user/jenkins/workspace/pipeline_job1/Docker
        cmd: docker-compose up -d #cmd: sudo docker-compose up -d