---
- hosts: module1
  become: true #become: false
  tasks:
    - name: docker compose up
      shell:
        #chdir: /home/ec2-user/jenkins/workspace/pipeline_job/Docker
        cmd: docker-compose up -d #cmd: sudo docker-compose up -d